title: "[Weekly Admin Curation Report]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to maintain WikiPathways as a high-quality resource!
  - type: textarea
    id: recent-changes
    attributes:
      label: Recent changes
      description: "Summarize recent changes"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: new-pathways
    attributes:
      label: New Pathways
      description: "List any new pathways this week, by WPID."
      placeholder: New Pathways
      value: "List of new pathways"
    validations:
      required: true
  - type: textarea
    id: deleted-pathways
    attributes:
      label: Deleted Pathways
      description: "List any pathways that were deleted, or if you do not have deletion rights, any pathways that are ready to be deleted."
      placeholder: Deleted Pathways
      value: "List of deleted pathways"
    validations:
      required: true
  - type: input
    id: notes
    attributes:
      label: Additional notes
      description: "List any other additional notes from this week's activities."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Update Approved pathway tag
      options:
        - label: All Approved pathways tags were updated!
          required: false
