title: "[Weekly Curation Report]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to maintain WikiPathways as a high-quality resource!
  - type: textarea
    id: recent-changes
    attributes:
      label: Recent changes
      description: "Summarize recent changes."
      value: "Recent Changes: "
    validations:
      required: true
  - type: textarea
    id: under-construction
    attributes:
      label: Under construction
      description: "Evalutate pathways under construction."
      value: "Under Construction: "
    validations:
      required: true
  - type: textarea
    id: new-pathways
    attributes:
      label: New pathways
      description: "List any new pathways this week, by WPID."
      placeholder: New Pathways
      value: "New pathways: "
    validations:
      required: true
  - type: textarea
    id: deleted-pathways
    attributes:
      label: Deleted Pathways
      description: "List any pathways that were deleted, or if you do not have deletion rights, any pathways that are ready to be deleted."
      placeholder: Deleted Pathways
      value: "Deleted pathways: "
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: "Share additional notes from this week's activities."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Update Approved pathway tag
      options:
        - label: All Approved pathways tags were updated!
          required: false
