title: "[Weekly Review Report]: Month Day - Day"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to maintain WikiPathways as a high-quality resource!
  - type: textarea
    id: recent-changes
    attributes:
      label: Recent changes
      description: "Summarize recent changes. If there were ANY recent changes that you reverted during your review, please add them [here](https://docs.google.com/spreadsheets/d/1TiIMqp001euqNpH0tVbN5PMD1x-uoXV0sj3Dq43aKkk/edit#gid=0)"
      value: " * ... "
    validations:
      required: true
  - type: textarea
    id: under-construction
    attributes:
      label: Under construction
      description: "Evaluate pathways under construction."
      value: " * ... "
    validations:
      required: true
  - type: textarea
    id: new-pathways
    attributes:
      label: New pathways
      description: "List any new pathways this week, by WPID."
      placeholder: New Pathways
      value: " * ... "
    validations:
      required: true
  - type: textarea
    id: deleted-pathways
    attributes:
      label: Deleted Pathways
      description: "List any pathways that were deleted, or if you do not have deletion rights, any pathways that are ready to be deleted."
      placeholder: Deleted Pathways
      value: " * ... "
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Update Approved pathway tag
      options:
        - label: All Approved pathways tags were updated!
          required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: "Share any additional notes from this week's activities. If any GitHub issues were opened, for example for problematic pathway, add the URLs to issues here."
    validations:
      required: false
