name: Weekly Admin Curation Report
description: A summary of your admin curation activities
title: "[Weekly Admin Curation Report]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to maintain WikiPathways as a high-quality resource!
  - type: textarea
    id: recent-changes
    attributes:
      label: Recent Changes
      description: Summarize recent changes
      placeholder: Recent Changes
      value: "Summary of recent changes"
    validations:
      required: true
  - type: textarea
    id: New Pathways
    attributes:
      label: New Pathways
      description: List any new pathways this week, preferably by WPID
      placeholder: New Pathways
      value: "List of new pathways"
    validations:
      required: false
 - type: textarea
    id: Deleted Pathways
    attributes:
      label: Deleted Pathways
      description: List any pathways that were deleted, or if you don't have deletion rights, any pathways that are ready to be deleted
      placeholder: Deleted Pathways
      value: "List of pathways for deletion"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Update Approved pathway tag
      options:
        - label: Update Approved tags 
          required: false
        - label: All Approved pathways tags were updated!
