title: "[Pathway Discussion]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for engaging the community and starting a discussion about the pathway! Pathway discussions may be transferred to [Pathway Curation Tasks](https://github.com/wikipathways/pathway-curation-tasks/issues) where appropriate.
  - type: textarea
    id: discussion-main
    attributes:
      label: Discussion
      description: Share your ideas and comments about the pathway with the community. Include links to any relevant external materials.
      placeholder: Discussion
      value: "This is a great pathway, but it could benefit from....."
    validations:
      required: true
  - type: checkboxes
    id: deletion
    attributes:
      label: Should this pathway be deleted?
      description: Let us know if you think this pathway is not appropriate and should be deleted.
      options:
        - label: Yes, this pathway should be deleted
          required: false
