title: "[Pathway Discussion]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for engaging the community and starting a discussion about the pathway! Pathway discussions may be transferred to [Pathway Curation Tasks](https://github.com/wikipathways/pathway-curation-tasks/issues) where appropriate.
  - type: textarea
    id: discussion-main
    attributes:
      label: Discussion
      description: Share your ideas and comments about the pathway with the community. Include links to any relevant external materials.
      placeholder: Discussion
    validations:
      required: true
  - type: input.multicheckbox
      label: Type of revision
      options:
        minor: Minor
        major: Major
        deletion: Deletion
    validations:
      required: true
