title: "[Weekly Admin Curation Report]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to maintain WikiPathways as a high-quality resource!
  - type: textarea
    id: recent-changes
    attributes:
      label: Recent changes
      description: "Summarize recent changes"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Update Approved pathway tag
      options:
        - label: All Approved pathways tags were updated!
          required: false
