name: Pathway Content
description: Report an issue with a pathway at WikiPathways
title: "[Pathway Content Issue]: "
labels: ["curation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: textarea
    id: issue-description
    attributes:
      label: What is the issue with the pathway?
      description: Include a detailed description of the issue and any proposed solution. Including links to relevant materials is also useful.
      placeholder: Describe the issue
      value: "There's an error in the pathway!"
    validations:
      required: true
  - type: dropdown
    id: issue-category
    attributes:
      label: What kind of content issue is this? 
      multiple: true
      options:
        - Missing content
        - Incorrect content
        - Duplicated content
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Should this pathway be deleted?
      description: Let us know if you think this pathway is not appropriate and should be deleted.
      options:
        - label: Pathway should be deleted
          required: false
