name: Pathway Content
description: Report an issue with a pathway at WikiPathways
title: "[Pathway Content Issue]: "
labels: ["curation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in WikiPathways and for helping us improve our content! Pathway issues may be transferred to [Pathway Curation Tasks](https://github.com/wikipathways/pathway-curation-tasks/issues) where appropriate.
  - type: textarea
    id: issue-description
    attributes:
      label: What is the problem with the pathway?
      description: Include a detailed description of any issues and any proposed solution. Including links to relevant materials is also useful.
      placeholder: Describe the issue
      value: 
    validations:
      required: true
  - type: dropdown
    id: issue-category
    attributes:
      label: What kind of content issue is this? 
      multiple: true
      options:
        - Missing content
        - Incorrect content
        - Duplicated content
        - Other
  - type: checkboxes
    id: revision-type
    attributes:
      label: Type of revision
      description: Let us know what type of revision you are proposing.
      options:
        - label: Major
        - label: Minor
        - label: Deletion
